config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root to: 'pages#home'

  devise_for :users

  resources :users, only: [:show]
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :events, except: [:destroy]
  resources :photos, only: [:destroy]

  namespace :api do
    resources :events
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events

  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_and_belongs_to_many :categories

  has_many :registrations, dependent: :destroy
  has_many :guests, through: :registrations, source: :user

  def self.asc_order_name
    order(name: :asc)
  end

  scope :published, -> { where(active: true)}

#  validates :name, presence: true
#  validates :description, presence: true, length: { maximum: 500 }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  
  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy

  has_one :profile

  has_many :registrations, dependent: :destroy
  has_many :booked_events, through: :registrations, source: :event

  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end

end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  def index
    render status: 200, json: {
      events: Event.all
    }.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

 def index
   @events = current_user.events
 end

 def show
   @categories = @event.categories
   @photos = @event.photos
 end

 def new
   @event = current_user.events.build
 end

 def create
   @event = current_user.events.build(event_params)
   if @event.save
     image_params.each do |image|
       @event.photos.create(image: image)
     end
     redirect_to @event, notice: "Event created"
   else
     render :new
   end
 end

 def edit
   if current_user.id == @event.user.id
     @photos = @event.photos
   else
     redirect_to @event, notice: "You don't have permission."
   end
 end

 def update
   if @event.update(event_params)
     image_params.each do |image|
       @event.photos.create(image: image)
     end
     redirect_to @event, notice: "Event updated"
   else
     render :edit
   end
 end

 private

 def set_event
   @event = Event.find(params[:id])
 end

 def image_params
   params[:images].present? ? params.require(:images) : []
 end

 def event_params
   params
     .require(:event)
     .permit(
       :name, :description, :location, :price, :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, :user, :image_link
     )
 end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>

  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, rows: 5, placeholder: "Something about your event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Location</label>
    <%= f.text_area :location, rows: 5, placeholder: "The location of your event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Image link</label>
    <%= f.text_area :image_link, rows: 5, placeholder: "The image link of your event", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.check_box :includes_food %> Includes food
  </div>
  <div class="form-group">
    <%= f.check_box :includes_drinks %> Includes drinks
  </div>

  <div class="form-group">
    <label>Price</label>
    <div class="input-group">
      <div class="input-group-addon">€</div>
      <%= f.number_field :price, placeholder: "eg. 100", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label>Capacity</label>
    <div class="input-group">
      <div class="input-group-addon">persons</div>
      <%= f.number_field :capacity, placeholder: "eg. 200", class: "form-control" %>
    </div>
  </div>

  <label>Categories</label>
  <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
    <div class="form-group">
      <%= b.check_box(class: "check_box") %> <%= b.object.name %>
    </div>
  <% end %>

  <label>Photos</label>
  <div class="form-group">
    <span class="btn btn-default">
      Upload Photos
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
  </div>

  <div id="photos">
    <%= render 'photos/list' %>
  </div>

  <label>Publish this?</label>

  <div class="form-group">
    <%= f.check_box :active %> Active
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your events", events_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your events
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">

    <p>Description: <%= @event.description %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p><%= @event.price %> euro</p>
    <p><%= @event.capacity %> <%= @event.capacity > 1 ? "persons" : "person" %></p>

    <!-- About -->
    <h4>About</h4>
    <p><%= @event.location %></p>

    <p><img src="<%= @event.image_link %>"></p>
    <p><%= @event.image_link %></p>

    <h4>Categories</h4>
    <% @categories.each do |category| %>
      <span class="label label-success"><%= category.name %></span>
    <% end %>

    <!-- Photos -->
    <h4>Photos</h4>
    <% @event.photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= image_tag photo.image.thumbnail %>
      </div>
    </div>
    <% end %>

    <!-- Amenities -->
    <h4>Amenities</h4>
    <ul class="amenities">
      <li><%= !@event.includes_food ? ("<del>Includes food</del>").html_safe : "Includes food" %></li>
      <li><%= !@event.includes_drinks ? ("<del>Includes drinks</del>").html_safe : "Includes drinks" %></li>
    </ul>
  </div>

</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>